#!/bin/bash
##d33vliter

i="sudo apt install -y"
i1="sudo apt install --no-install-recommends -y"

##paquetes para compilar
	$i linux-headers-$(uname -r) build-essential make automake pkg-config cmake autoconf git

##programas base
	$i xinit nitrogen tint2 geany neofetch slim sakura volumeicon-alsa \
	 alsa-utils ntp yad elogind viewnior xdg-user-dirs at-spi2-core thunar thunar-archive-plugin libexo-1-0

##paquetes sin recomendados
	$i1 firefox-esr mpv lxappearance gtk2-engines-murrine gtk2-engines-pixbuf xfce4-notifyd libnotify-bin xbacklight

##openbox
	$i1 openbox openbox-menu lxmenu-data obmenu arandr xarchiver p7zip-full wicd-curses conky

clear
echo "Aplicando configuraciones..."
sleep 2s

##config
xdg-user-dirs-update
mkdir -p $HOME/.config/openbox
mkdir -p $HOME/.config/tint2
echo -e "nitrogen --restore &
\ntint2 &
\nconky &
\nvolumeicon &
\n/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &" > $HOME/.config/openbox/autostart.sh
cp -r cfg/menu.xml $HOME/.config/openbox/
cp -r tint2/laptop/tint2rc $HOME/.config/tint2/
cp -r tint2/laptop/minimo-laptop.tint2rc $HOME/.config/tint2/
cp -r cfg/rc.xml $HOME/.config/openbox/
cp -r cfg/.conkyrc $HOME/
cp -r cfg/.themes $HOME/
sudo cp -r cfg/exit /usr/bin/
sudo cp -r cfg/slim/default /usr/share/slim/themes/
echo -e "exec dbus-launch --sh-syntax --exit-with-session openbox-session" > $HOME/.xinitrc
##configuraciones para laptop
$i xserver-xorg-input-synaptics
echo -e "\nsynclient TapButton1=1 &" >> $HOME/.config/openbox/autostart.sh
####
clear
echo "Instalación completada"
echo "pulse cualquiera tecla para continuar..."
read tecla
clear
